=== heathermhuang/cbi-data/schemas/cost.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "programmeId": {
      "type": "string"
    },
    "optionId": {
      "type": "string"
    },
    "claimId": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "programmeId",
    "optionId",
    "claimId"
  ]
}

=== heathermhuang/cbi-data/data/costs/cbi-slv.json
[
  {
    "id": "cbi-slv-scenario-item-24",
    "programmeId": "cbi-slv",
    "optionId": "cbi-slv-option-1",
    "claimId": "cbi-slv-scenario-item-24"
  },
  {
    "id": "cbi-slv-scenario-item-25",
    "programmeId": "cbi-slv",
    "optionId": "cbi-slv-option-1",
    "claimId": "cbi-slv-scenario-item-25"
  }
]

=== heathermhuang/cbi-data/data/costs/cbi-atg.json
[
  {
    "id": "cbi-atg-cost-0",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-cost-0"
  },
  {
    "id": "cbi-atg-cost-1",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-cost-1"
  },
  {
    "id": "cbi-atg-cost-2",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-cost-2"
  },
  {
    "id": "cbi-atg-cost-18",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-cost-18"
  },
  {
    "id": "cbi-atg-cost-19",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-cost-19"
  },
  {
    "id": "cbi-atg-cost-20",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-cost-20"
  },
  {
    "id": "cbi-atg-cost-21",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-cost-21"
  },
  {
    "id": "cbi-atg-dated-cost-7",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-dated-single-fee-7"
  },
  {
    "id": "cbi-atg-scenario-item-32",
    "programmeId": "cbi-atg",
    "optionId": "cbi-atg-option-1",
    "claimId": "cbi-atg-scenario-item-32"
  }
]

=== heathermhuang/cbi-data/data/costs/cbi-kna.json
[
  {
    "id": "cbi-kna-dated-cost-0",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-dated-single-fee-0"
  },
  {
    "id": "cbi-kna-dated-cost-1",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-dated-single-fee-1"
  },
  {
    "id": "cbi-kna-dated-cost-2",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-dated-single-fee-2"
  },
  {
    "id": "cbi-kna-scenario-item-27",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-27"
  },
  {
    "id": "cbi-kna-scenario-item-28",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-28"
  },
  {
    "id": "cbi-kna-scenario-item-29",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-29"
  },
  {
    "id": "cbi-kna-scenario-item-30",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-30"
  },
  {
    "id": "cbi-kna-scenario-item-31",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-31"
  },
  {
    "id": "cbi-kna-scenario-item-32",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-32"
  },
  {
    "id": "cbi-kna-scenario-item-33",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-33"
  },
  {
    "id": "cbi-kna-scenario-item-34",
    "programmeId": "cbi-kna",
    "optionId": "cbi-kna-option-1",
    "claimId": "cbi-kna-scenario-item-34"
  }
]

=== heathermhuang/cbi-data/data/costs/cbi-vut.json
[
  {
    "id": "cbi-vut-cost-4",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-4"
  },
  {
    "id": "cbi-vut-cost-5",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-5"
  },
  {
    "id": "cbi-vut-cost-6",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-6"
  },
  {
    "id": "cbi-vut-cost-7",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-7"
  },
  {
    "id": "cbi-vut-cost-23",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-23"
  },
  {
    "id": "cbi-vut-cost-24",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-24"
  },
  {
    "id": "cbi-vut-cost-25",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-25"
  },
  {
    "id": "cbi-vut-cost-26",
    "programmeId": "cbi-vut",
    "optionId": "cbi-vut-option-1",
    "claimId": "cbi-vut-cost-26"
  }
]

=== heathermhuang/cbi-data/data/costs/cbi-grd.json
[
  {
    "id": "cbi-grd-dated-cost-0",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-dated-single-fee-0"
  },
  {
    "id": "cbi-grd-dated-cost-1",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-dated-single-fee-1"
  },
  {
    "id": "cbi-grd-dated-cost-2",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-dated-single-fee-2"
  },
  {
    "id": "cbi-grd-dated-cost-3",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-dated-single-fee-3"
  },
  {
    "id": "cbi-grd-dated-cost-4",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-dated-single-fee-4"
  },
  {
    "id": "cbi-grd-scenario-item-29",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-scenario-item-29"
  },
  {
    "id": "cbi-grd-scenario-item-30",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-scenario-item-30"
  },
  {
    "id": "cbi-grd-scenario-item-31",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-scenario-item-31"
  },
  {
    "id": "cbi-grd-scenario-item-32",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-scenario-item-32"
  },
  {
    "id": "cbi-grd-scenario-item-33",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-scenario-item-33"
  },
  {
    "id": "cbi-grd-scenario-item-34",
    "programmeId": "cbi-grd",
    "optionId": "cbi-grd-option-1",
    "claimId": "cbi-grd-scenario-item-34"
  }
]

=== heathermhuang/cbi-data/data/costs/cbi-nru.json
[
  {
    "id": "cbi-nru-cost-10",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-cost-10"
  },
  {
    "id": "cbi-nru-cost-11",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-cost-11"
  },
  {
    "id": "cbi-nru-cost-12",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-cost-12"
  },
  {
    "id": "cbi-nru-cost-13",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-cost-13"
  },
  {
    "id": "cbi-nru-cost-14",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-cost-14"
  },
  {
    "id": "cbi-nru-scenario-item-28",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-scenario-item-28"
  },
  {
    "id": "cbi-nru-scenario-item-29",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-scenario-item-29"
  },
  {
    "id": "cbi-nru-scenario-item-30",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-scenario-item-30"
  },
  {
    "id": "cbi-nru-scenario-item-31",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-scenario-item-31"
  },
  {
    "id": "cbi-nru-scenario-item-32",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-scenario-item-32"
  },
  {
    "id": "cbi-nru-scenario-item-33",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-scenario-item-33"
  },
  {
    "id": "cbi-nru-scenario-item-34",
    "programmeId": "cbi-nru",
    "optionId": "cbi-nru-option-1",
    "claimId": "cbi-nru-scenario-item-34"
  }
]

=== heathermhuang/cbi-data/data/costs/cbi-lca.json
[
  {
    "id": "cbi-lca-cost-9",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-cost-9"
  },
  {
    "id": "cbi-lca-cost-28",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-cost-28"
  },
  {
    "id": "cbi-lca-scenario-item-26",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-scenario-item-26"
  },
  {
    "id": "cbi-lca-scenario-item-27",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-scenario-item-27"
  },
  {
    "id": "cbi-lca-scenario-item-28",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-scenario-item-28"
  },
  {
    "id": "cbi-lca-scenario-item-29",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-scenario-item-29"
  },
  {
    "id": "cbi-lca-scenario-item-30",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-scenario-item-30"
  },
  {
    "id": "cbi-lca-scenario-item-31",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-option-1",
    "claimId": "cbi-lca-scenario-item-31"
  },
  {
    "id": "cbi-lca-built-property-single_adult-capital",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-built-property",
    "claimId": "cbi-lca-built-property-single_adult-capital"
  },
  {
    "id": "cbi-lca-built-property-single_adult-government_charge",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-built-property",
    "claimId": "cbi-lca-built-property-single_adult-government_charge"
  },
  {
    "id": "cbi-lca-built-property-couple_two_children_under12-capital",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-built-property",
    "claimId": "cbi-lca-built-property-couple_two_children_under12-capital"
  },
  {
    "id": "cbi-lca-built-property-couple_two_children_under12-government_charge",
    "programmeId": "cbi-lca",
    "optionId": "cbi-lca-built-property",
    "claimId": "cbi-lca-built-property-couple_two_children_under12-government_charge"
  }
]

=== heathermhuang/cbi-data/data/costs/cbi-dma.json
[
  {
    "id": "cbi-dma-cost-3",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-cost-3"
  },
  {
    "id": "cbi-dma-cost-22",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-cost-22"
  },
  {
    "id": "cbi-dma-dated-cost-2",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-dated-single-fee-2"
  },
  {
    "id": "cbi-dma-dated-cost-3",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-dated-single-fee-3"
  },
  {
    "id": "cbi-dma-dated-cost-4",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-dated-single-fee-4"
  },
  {
    "id": "cbi-dma-dated-cost-5",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-dated-single-fee-5"
  },
  {
    "id": "cbi-dma-scenario-item-30",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-scenario-item-30"
  },
  {
    "id": "cbi-dma-scenario-item-31",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-scenario-item-31"
  },
  {
    "id": "cbi-dma-scenario-item-32",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-scenario-item-32"
  },
  {
    "id": "cbi-dma-scenario-item-33",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-scenario-item-33"
  },
  {
    "id": "cbi-dma-scenario-item-34",
    "programmeId": "cbi-dma",
    "optionId": "cbi-dma-option-1",
    "claimId": "cbi-dma-scenario-item-34"
  }
]
